version: '3'

services:

  webserver:
    image: nginx:1.25.1-alpine3.17
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html/public

  db:
    env_file:
      - mariadb.local.env
    environment:
      MYSQL_DATABASE: lamp_db
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    image: mariadb:11.0.2-jammy
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/mysql

  php:
    build: './php/'
    restart: unless-stopped
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./www:/var/www/html/public
