version: '3'

services:

  webserver:
    image: nginx:1.21.4-alpine
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html/public

  db:
    env_file:
      - .local.env
    environment:
      MYSQL_DATABASE: lamp_db
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    image: mariadb:10.7.1-focal
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/mysql

  php:
    build:
      context: ./php/
      dockerfile: Dockerfile.legacy
    restart: unless-stopped
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./www:/var/www/html/public
